import React, { useState } from 'react';
import { Input, Button } from 'semantic-ui-react'
import Head from 'next/head'
import Router from 'next/router';
import styles from '../../styles/Home.module.css'
import { isPassengerExist } from '../../utils/passenger-utils';


export default function LoginPassenger() {
    const [passengerID, setPassengerID] = useState(''); // '' is the initial state value

    async function loginAsPassenger() {
        if (passengerID != '') {
            let exist = await isPassengerExist(passengerID);
            if (exist) {
                Router.push(`/passenger/${passengerID}`)
            } else {
                alert("Incorrect passenger credential information to login!")
            }
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Login as a passenger
                </h1>

                <p className={styles.description}>
                    You will be prompted to enter your <span className={styles.blueColor}>passenger id</span> in order to login.
                </p>

                <Input value={passengerID} onChange={e => setPassengerID(e.target.value)} focus placeholder='Enter your passenger id' />
                <br />
                <Button onClick={loginAsPassenger} primary>Login</Button>
            </main>

        </div>
    )
}

