import { getStaticPathForPassengers } from '../../../utils/passenger-utils';
import Head from 'next/head'
import styles from '../../../styles/Home.module.css'

export async function getStaticProps({ params }) {
    const passengerID = params.id
    return {
        props: {
            passengerID
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForPassengers();

    return {
        paths,
        fallback: false
    }
}

export default function DriverHome({ passenger_id }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Trip</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                Create Trip
            </h1>


        </div>
    )
}