import { getPassenger, getStaticPathForPassengers } from '../../../utils/passenger-utils';
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'

export async function getStaticProps({ params }) {
    const passengerID = params.id
    const passenger = await getPassenger(passengerID);
    return {
        props: {
            ...passenger
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForPassengers();

    return {
        paths,
        fallback: false
    }
}

export default function DriverHome({ passenger_id, last_name, first_name }) {
    let editProfileLink = `${passenger_id}/edit`;
    let viewTripLink = `${passenger_id}/trips`

    return (
        <div className={styles.container}>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    U are now signed in as {last_name} {first_name} #{passenger_id}
                </h1>

                <br />

                <div className={styles.grid}>
                    <Link href={editProfileLink}>
                        <a className={styles.card}>
                            <h2>Edit passenger profile &rarr;</h2>
                            <p>Edit your passenger profile to keep your profile <span className={styles.blueColor}> up-to-date </span></p>
                        </a>
                    </Link>

                    <Link href={viewTripLink}>
                        <a className={styles.card}>
                            <h2>View past trips &rarr;</h2>
                            <p>View past completed trips in the table</p>
                        </a>
                    </Link>
                </div>
            </main>

        </div>
    )
}