import { getPassenger, getStaticPathForPassengers } from '../../../utils/passenger-utils';
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'

export async function getStaticProps({ params }) {
    const passengerID = params.id
    const passenger = await getPassenger(passengerID);
    return {
        props: {
            ...passenger
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForPassengers();

    return {
        paths,
        fallback: false
    }
}

export default function DriverHome({ passenger_id, last_name, first_name, available_status }) {
    let editProfileLink = `${passenger_id}/edit`;
    let viewTripsLink = `${passenger_id}/view_trips`
    let createTripLink = `${passenger_id}/create_trip`


    return (
        <div className={styles.container}>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    U are now signed in as {last_name} {first_name} #{passenger_id}
                </h1>

                {available_status == 2 &&
                    <p className={styles.description}>
                        You are currently in an <span className={styles.blueColor}>ongoing</span> trip
                    </p>
                }

                <br />

                <div className={styles.grid}>
                    {available_status == 1 &&
                        <Link href={createTripLink}>
                            <a className={styles.card}>
                                <h2>Create Trip &rarr;</h2>
                                <p>Create a trip and the platform will assign an <span className={styles.blueColor}> available </span>driver for you</p>
                            </a>
                        </Link>
                    }

                    <Link href={editProfileLink}>
                        <a className={styles.card}>
                            <h2>Edit passenger profile &rarr;</h2>
                            <p>Edit your passenger profile to keep your profile <span className={styles.blueColor}> up-to-date </span></p>
                        </a>
                    </Link>

                    <Link href={viewTripsLink}>
                        <a className={styles.card}>
                            <h2>View past trips &rarr;</h2>
                            <p>View past completed trips in the table</p>
                        </a>
                    </Link>
                </div>
            </main>

        </div>
    )
}