import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ride Sharing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Ride Sharing!
        </h1>

        <p className={styles.description}>
          Login or create an account as a <span className={styles.blueColor}>driver</span> or <span className={styles.blueColor}>passenger</span>
        </p>

        <div className={styles.grid}>
          <Link href='/login/passenger'>
            <a className={styles.card}>
              <h2>Login as a passenger &rarr;</h2>
              <p>You will be prompted to enter your <span className={styles.blueColor}> passenger id </span> in order to login.</p>
            </a>
          </Link>

          <Link href='/login/driver'>
            <a className={styles.card}>
              <h2>Login as a driver &rarr;</h2>
              <p>You will be prompted to enter your <span className={styles.blueColor}>driver id</span> in order to login.</p>
            </a>
          </Link>

          <Link href='/register/passenger'>
            <a className={styles.card}>
              <h2>Register as a passenger&rarr;</h2>
              <p>You will be required to enter your basic information during registration.</p>
            </a>
          </Link>

          <Link href='/register/driver'>
            <a className={styles.card}>
              <h2>Register as a driver &rarr;</h2>
              <p>You will be required to enter your basic and additional driver information during registration.</p>
            </a>
          </Link>
        </div>
      </main>

    </div>
  )
}
