version: '3.9'
services:
  general_server:
    container_name: general_purpose_server
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*