import React from 'react'
import Head from 'next/head'
import { Button, Table } from 'semantic-ui-react'
import styles from '../../../styles/Home.module.css'
import { getStaticPathForDrivers, initiateTripAsDriver, retrieveAvailableTripsForDriver } from '../../../utils/driver-utils'
import Router from 'next/router';
import { formatDateStringFromMs } from '../../../utils/date-utils'

export async function getStaticProps({ params }) {
    const driverID = params.id
    const trips = await retrieveAvailableTripsForDriver(driverID);

    return {
        props: {
            driverID,
            trips
        }
    }
}

export async function getStaticPaths() {
    const paths = await getStaticPathForDrivers();

    return {
        paths,
        fallback: false
    }
}

export default function ViewTrips({ driverID, trips }) {

    const rows = trips != null ? trips.map(function (trip) {
        return (
            <Table.Row key={trip.trip_id}>
                <Table.Cell>{trip.trip_id}</Table.Cell>
                <Table.Cell>{`${trip.passenger.last_name} ${trip.passenger.first_name} #${trip.passenger.passenger_id}`}</Table.Cell>
                <Table.Cell>{`${trip.driver.last_name} ${trip.driver.first_name} #${trip.driver.driver_id}`}</Table.Cell>
                <Table.Cell>{trip.pickup_postal_code}</Table.Cell>
                <Table.Cell>{trip.dropoff_postal_code}</Table.Cell>
                <Table.Cell>{formatDateStringFromMs(trip.created_time)}</Table.Cell>
                <Table.Cell>{formatDateStringFromMs(trip.completed_time)}</Table.Cell>
                <Table.Cell><Button onClick={() => initiateTrip(trip.trip_id)} >Initiate</Button></Table.Cell>
            </Table.Row>
        )
    }) : 'There is no available trip to be initiated yet'

    async function initiateTrip(trip_id) {
        let response = await initiateTripAsDriver(trip_id, driverID)
        if (response.status == 202) {
            Router.push(`/driver/${driverID}`)
        } else {
            alert(response.data)
        }
    }

    return (

        <div className={styles.container}>
            <Head>
                <title>Initiate a Trip</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
                Initiate a Trip
            </h1>

            <br />

            <Table celled>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell>TripID</Table.HeaderCell>
                        <Table.HeaderCell>Passenger</Table.HeaderCell>
                        <Table.HeaderCell>Driver</Table.HeaderCell>
                        <Table.HeaderCell>PickupPostalCode</Table.HeaderCell>
                        <Table.HeaderCell>DropoffPostalCode</Table.HeaderCell>
                        <Table.HeaderCell>CreatedTime</Table.HeaderCell>
                        <Table.HeaderCell>CompletedTime</Table.HeaderCell>
                        <Table.HeaderCell>Actions</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    {rows}
                </Table.Body>

            </Table>

        </div>
    )
}