version: '3.9'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*